name: AoC2023
version: 0.1.0.0
github: "Per48edjes/AoC2023"
license: BSD-3-Clause
author: "Ravi Dayabhai"
maintainer: "r.i.dayabhai@gmail.com"
copyright: "2023 Ravi Dayabhai"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/Per48edjes/AoC2023#readme>

dependencies:
  - base >= 4.7 && < 5

default-extensions:
  - GADTs
  - LambdaCase
  - OverloadedStrings
  - RecordWildCards
  - StandaloneDeriving
  - TupleSections
  - TypeApplications

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs:
    - src
  exposed-modules:
    - Util
    - Day01.Part1
    - Day01.Part2
    - Day02.Part1
    - Day02.Part2
    - Day03.Part1
    - Day03.Part2
    - Day04.Part1
    - Day04.Part2
    - Day05.Part1
    - Day05.Part2
    - Day06.Part1
    - Day06.Part2
    - Day07.Part1
    - Day07.Part2
    - Day08.Part1
    - Day08.Part2
    - Day09.Part1
    - Day09.Part2
    - Day10.Part1
    - Day10.Part2
    - Day11.Part1
    - Day11.Part2
    - Day12.Part1
    - Day12.Part2
    - Day13.Part1
    - Day13.Part2
    - Day14.Part1
    - Day14.Part2
    - Day15.Part1
    - Day15.Part2
    # Placeholder for Day 16
    # Placeholder for Day 16
    - Day17.Part1
    - Day17.Part2
  dependencies:
    - mtl
    - array
    - attoparsec
    - megaparsec
    - bytestring
    - containers
    - extra
    - errors
    - heap
    - memoize
    - split
    - text
    - unordered-containers
    - vector

executables:
  AoC2023-exe:
    main: Main.hs
    source-dirs: solutions
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - AoC2023

tests:
  AoC2023-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - AoC2023
      - unordered-containers
      - attoparsec
      - megaparsec
      - containers
      - hspec
      - hspec-expectations
      - silently
      - QuickCheck
      - text
      - vector
